# Generated by Django 4.1 on 2022-08-19 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='openning_times_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Время работы'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='openning_times_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Время работы'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='openning_times_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Время работы'),
        ),
        migrations.AddField(
            model_name='sale',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Афиша'),
        ),
        migrations.AddField(
            model_name='sale',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Афиша'),
        ),
        migrations.AddField(
            model_name='sale',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Афиша'),
        ),
        migrations.AddField(
            model_name='sale',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='sale',
            name='text_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='sale',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='selection',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='selection',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='selection',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
