# Generated by Django 4.1 on 2022-08-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='instagram',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Сcылка на Instagram'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='site',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Ссылка на сайт'),
        ),
    ]
