# Generated by Django 4.1 on 2022-08-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_category_name_en_category_name_ky_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='category_ky',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='category_ru',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='selection',
            field=models.ManyToManyField(blank=True, to='rest.selection', verbose_name='Подборки'),
        ),
    ]
