# Generated by Django 4.1 on 2022-08-15 05:57

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_restaurant_instagram_restaurant_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='phone_number_1',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='phone_number_2',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='phone_number_3',
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_number', to='rest.restaurant')),
            ],
        ),
    ]
