# Generated by Django 4.1 on 2022-08-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_remove_restaurant_phone_number_1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
    ]
