# Generated by Django 4.1 on 2022-08-22 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_bars_cafes_clubs_coffeehouses_restaurants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='bars',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='cafes',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='clubs',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='coffee_houses',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurants',
        ),
        migrations.DeleteModel(
            name='Bars',
        ),
        migrations.DeleteModel(
            name='Cafes',
        ),
        migrations.DeleteModel(
            name='Clubs',
        ),
        migrations.DeleteModel(
            name='CoffeeHouses',
        ),
        migrations.DeleteModel(
            name='Restaurants',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest.category', verbose_name='Категория'),
        ),
    ]
