# Generated by Django 4.1 on 2022-08-16 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_rename_contacts_contact_alter_contact_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='rest.restaurant'),
        ),
        migrations.AlterField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='rest.restaurant'),
        ),
    ]
